name: "rapiddweller-benerator-ce CI"

on:
  push:
    branches: [ ci-migration ]
  pull_request:
    branches: [ ci-migration ]


jobs:

###################### Test / Build ######################

  build_jdk11:
    runs-on: ubuntu-20.04
    container: maven:3.6-adoptopenjdk-11
    env:
      ARTIFACT_ID: "rapiddweller-benerator-ce"
      ARTIFACT_VERSION_BASE: "1.1.0"
      MAVEN_CLI_OPTS: "--batch-mode"
    steps:
      - run: export
      - run: mvn -v
      - uses: actions/checkout@v2
      - run: mvn versions:set -DnewVersion=$ARTIFACT_VERSION_BASE-SNAPSHOT
      - run: mvn $MAVEN_CLI_OPTS clean package -Dmaven.test.skip=true
      - name: Upload build artifact for assembly
        uses: actions/upload-artifact@v2
        with:
          name: build_jdk11
          path: target/*.jar
          if-no-files-found: error
          retention-days: 5

  
  test_jdk11:
    runs-on: ubuntu-20.04
    container: maven:3.6-adoptopenjdk-11
    env:
      ARTIFACT_ID: "rapiddweller-benerator-ce"
      ARTIFACT_VERSION_BASE: "1.1.0"
      MAVEN_CLI_OPTS: "--batch-mode"
    steps:
      - run: export
      - run: mvn -v
      - uses: actions/checkout@v2    
      - run: mvn versions:set -DnewVersion=$ARTIFACT_VERSION_BASE-SNAPSHOT
      - run: mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
      - run: awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
      - run: ls
      - name: Upload test-report result for coverage_jdk11
        uses: actions/upload-artifact@v2
        with:
          name: test_jdk11
          entrypoint: target/site/jacoco/
          path: target/site/jacoco/jacoco.xml
          if-no-files-found: error
          retention-days: 5

###################### Quality ######################

  coverage_jdk11:
    runs-on: ubuntu-20.04
    container: haynes/jacoco2cobertura:1.0.4
    needs: ["test_jdk11"]
    steps:
      - name: Download test-report result from test_jdk11
        uses: actions/download-artifact@v2
        with:
          name: test_jdk11
          path: target/site/jacoco/jacoco.xml
      - run: ls
      - run: 'python /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java > cobertura.xml'
      - run: 'python /opt/source2filename.py cobertura.xml'
      - name: Upload cobertura report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_jdk11
          path: cobertura.xml

############################# Documentation ##############################

  documentation_build:
    runs-on: ubuntu-20.04
    container: python:3.9
    steps:
      - uses: actions/checkout@v2
      - run: pip install mkdocs-material
      - run: pip install markdown-include
      - run: pip install mkdocs-markdownextradata-plugin
      - run: pip install mkdocs-with-pdf
      - run: mkdocs build --clean
      - name: Upload documentation build for Assembly
        uses: actions/upload-artifact@v2
        with:
          name: documentation_build_assembly
          path: |
            site
            !*.pdf
      - name: Upload documentation build for hosting
        uses: actions/upload-artifact@v2
        with:
          name: documentation_build_hosting
          path: site

###################### Assembly and Deploy ######################

  assembly_jdk11:
    runs-on: ubuntu-20.04
    container: maven:3.6-adoptopenjdk-11
    env:
      ARTIFACT_ID: "rapiddweller-benerator-ce"
      ARTIFACT_VERSION_BASE: "1.1.0"
      MAVEN_CLI_OPTS: "--batch-mode"
    needs: [build_jdk11,documentation_build]
    steps:
      - uses: actions/checkout@v2    
      - run: mvn versions:set -DnewVersion=$ARTIFACT_VERSION_BASE-SNAPSHOT
      - name: Download build_jdk11 for assembly
        uses: actions/download-artifact@v2
        with:
          name: build_jdk11
      - name: Download documentation_build_assembly for assembly
        uses: actions/download-artifact@v2
        with:
          name: documentation_build_assembly
      - run: ls
      - run: cd target && ls && cd ..
      - run: mvn $MAVEN_CLI_OPTS site:site assembly:single -Dmaven.test.skip=true
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: assembly_jdk11
          path: |
            target/*.tar.gz
            target/*.zip
            target/site/
