on:
  push

env:
  MAVEN_CLI_OPTS: "--batch-mode --update-snapshots"
  JAVA_JDKVERSION_TAG: "jdk-11"
  SET_VERSION: |
    ARTIFACT_ID=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec);
    echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV;
jobs:
  ###################### Setup ######################
  setup:
    runs-on: ubuntu-latest
    container: maven:3.6-adoptopenjdk-11
    defaults:
      run:
        shell: bash
    steps:
      - run: export
      - uses: actions/checkout@v2
      - name: set ARTIFACT_ID
        run: |
          ARTIFACT_ID=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec);
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV;
      - name: set RELEASE version
        run: |
          ARTIFACT_VERSION=${GITHUB_REF/refs\/tags\//}-$JAVA_JDKVERSION_TAG;
          echo ARTIFACT_VERSION=$ARTIFACT_VERSION  >> $GITHUB_ENV;
          echo ARTIFACT_FULLNAME=$ARTIFACT_ID-$ARTIFACT_VERSION >> $GITHUB_ENV;
        if: startsWith(github.ref, 'refs/tags/')
      - name: set SNAPSHOT version
        run: |
          ARTIFACT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec);
          echo ARTIFACT_VERSION=$ARTIFACT_VERSION  >> $GITHUB_ENV;
          echo ARTIFACT_FULLNAME=$ARTIFACT_ID-$ARTIFACT_VERSION >> $GITHUB_ENV;
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      - name: set ARTIFACT_FULLNAME
        run: |
          echo "echo ARTIFACT_ID=${ARTIFACT_ID} >> \$GITHUB_ENV" >> dot.env
          echo "echo ARTIFACT_VERSION=${ARTIFACT_VERSION} >> \$GITHUB_ENV" >> dot.env
          echo "echo ARTIFACT_FULLNAME=${ARTIFACT_FULLNAME} >> \$GITHUB_ENV" >> dot.env
      - run: export
      - name: Upload setupfile
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: dot.env
          if-no-files-found: error
          retention-days: 1

  ###################### Test / Build ######################

  test_jdk11:
    runs-on: ubuntu-latest
    needs:
      - setup
    container: maven:3.6-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Download dot.env
        uses: actions/download-artifact@v2
        with:
          name: setup
      - run: bash dot.env
      - run: mvn versions:set -DnewVersion=$ARTIFACT_VERSION
      - run: mvn $MAVEN_CLI_OPTS clean test