on:

  push:
    branches:
      - development
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - development
    paths-ignore:
      - '**.md'

env:
  MAVEN_CLI_OPTS: "--batch-mode --update-snapshots"

jobs:
  ###################### Sonar ######################

  sonar:
    if: ${{ (!contains(github.event.head_commit.message, 'dependabot'))  && (!contains(github.event.head_commit.message, 'Bump')) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: maven:3.6-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: run UT genrate report
        run: mvn $MAVEN_CLI_OPTS clean verify -DskipITs=true
      - name: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=rapiddweller_rapiddweller-benerator-ce
